import {
    AsyncSystem,
    AsyncSystemNamesForStage,
    System,
    SystemGraph,
    SystemGraphArgs,
    SystemNamesForStage,
    SystemOrder,
    SystemStage,
} from './system';

export function arraySwapDelete<Item>(arr: Item[], idx: number) {
    arr[idx] = arr[arr.length - 1];
    return arr.pop();
}

export function objectKeys<Obj extends Record<string, unknown>>(obj: Obj) {
    return Object.keys(obj) as (keyof Obj)[];
}

export function warnAboutSingleAsyncSystem<Systems extends Record<string, System | AsyncSystem>, S extends SystemStage>(
    stage: SystemStage,
    order: SystemOrder<SystemNamesForStage<Systems, S>, AsyncSystemNamesForStage<Systems, S>>,
) {
    const asyncOnly = order.filter((element) => Array.isArray(element) && element.length < 2);
    if (asyncOnly.length > 0) {
        console.warn(
            `Only a single async system in order definition of stage: "${stage}". Consider making the system sync or add another async system.`,
        );
    }
}

export function defaultSystemOrder<Systems extends Record<string, System | AsyncSystem>, S extends SystemStage>(
    systems: Systems,
    stage: S,
): SystemOrder<SystemNamesForStage<Systems, S>, AsyncSystemNamesForStage<Systems, S>> {
    type T = SystemOrder<SystemNamesForStage<Systems, S>, AsyncSystemNamesForStage<Systems, S>>;

    const systemNamesForStage = objectKeys(systems).filter((key) => systems[key].stage === stage);
    const syncSystemNames = systemNamesForStage.filter((key) => !systems[key].async);
    const asyncSystemNames = systemNamesForStage.filter((key) => systems[key].async);

    if (syncSystemNames.length === 0 && asyncSystemNames.length === 0) {
        return [];
    }

    if (syncSystemNames.length === 0) {
        return [asyncSystemNames] as T;
    }

    if (asyncSystemNames.length === 0) {
        return syncSystemNames as T;
    }

    const order: T = [];
    const firstAsyncSystem = asyncSystemNames[0];
    const idxOfFirstAsyncSystem = systemNamesForStage.findIndex((key) => key === firstAsyncSystem);

    for (let i = 0; i < systemNamesForStage.length; i++) {
        const systemNameForStage = systemNamesForStage[i];

        if (i === idxOfFirstAsyncSystem) {
            order.push(asyncSystemNames as never);
        } else if (!systems[systemNameForStage].async) {
            order.push(systemNameForStage as never);
        }
    }

    return order;
}

export function validateSystemOrder<Systems extends Record<string, System | AsyncSystem>, S extends SystemStage>(
    systems: Systems,
    stage: S,
    order: SystemOrder<SystemNamesForStage<Systems, S>, AsyncSystemNamesForStage<Systems, S>>,
) {
    const systemNamesForStage = objectKeys(systems).filter((key) => systems[key].stage === stage);
    const flatOrderLength = order.flat().length;
    if (flatOrderLength !== systemNamesForStage.length) {
        throw new Error(
            `The order within the same stage must contain all system names exactly once. System count for stage "${stage}": ${systemNamesForStage.length}. Count of flattened order: ${flatOrderLength}`,
        );
    }

    return order;
}

type MergeRuleBefore<T> = { before: T };
type MergeRuleAfter<T> = { after: T };

export type MergeRules<A extends SystemGraphArgs, B extends SystemGraphArgs> = Partial<{
    [K in keyof B['systems']]:
        | MergeRuleBefore<
              | SystemNamesForStage<A['systems'], B['systems'][K]['stage']>
              | AsyncSystemNamesForStage<A['systems'], B['systems'][K]['stage']>
              | SystemNamesForStage<B['systems'], B['systems'][K]['stage']>
              | AsyncSystemNamesForStage<B['systems'], B['systems'][K]['stage']>
          >
        | MergeRuleAfter<
              | SystemNamesForStage<A['systems'], B['systems'][K]['stage']>
              | AsyncSystemNamesForStage<A['systems'], B['systems'][K]['stage']>
              | SystemNamesForStage<B['systems'], B['systems'][K]['stage']>
              | AsyncSystemNamesForStage<B['systems'], B['systems'][K]['stage']>
          >;
}>;

function isMergeRuleBefore(rule: unknown): rule is MergeRuleBefore<string> {
    return rule !== null && typeof rule === 'object' && 'before' in rule && typeof rule.before === 'string';
}

function isMergeRuleAfter(rule: unknown): rule is MergeRuleAfter<string> {
    return rule !== null && typeof rule === 'object' && 'after' in rule && typeof rule.after === 'string';
}

function flattenWithGroups(order: SystemOrder) {
    const result: Array<{ name: string; groupIdx: number; posInGroup: number }> = [];

    order.forEach((item, groupIdx) => {
        if (Array.isArray(item)) {
            item.forEach((name, posInGroup) => {
                result.push({ name: name.toString(), groupIdx, posInGroup });
            });
        } else {
            result.push({ name: item.toString(), groupIdx, posInGroup: 0 });
        }
    });

    return result;
}

// Generated by Claude - Sonnet 4.5
export function mergeSystemOrder(
    a: SystemOrder,
    b: SystemOrder,
    rules: MergeRules<SystemGraphArgs, SystemGraphArgs>,
    systems: Record<string, System | AsyncSystem>,
): SystemOrder {
    // Flatten to get all system names with their group info
    const flatA = flattenWithGroups(a);
    const flatB = flattenWithGroups(b);

    const isAsync = (name: string) => systems[name].async;

    // Build a merged list respecting rules
    const merged: (string | number | symbol)[] = [];
    const processedB = new Set<string | number | symbol>();

    for (const itemA of flatA) {
        // Find all B items that should go before this A item
        for (const itemB of flatB) {
            if (processedB.has(itemB.name)) continue;

            const rule = rules[itemB.name.toString()];
            if (isMergeRuleBefore(rule) && rule.before === itemA.name) {
                merged.push(itemB.name);
                processedB.add(itemB.name);
            }
        }

        // Add the A item
        merged.push(itemA.name);

        // Find all B items that should go after this A item
        for (const itemB of flatB) {
            if (processedB.has(itemB.name)) continue;

            const rule = rules[itemB.name.toString()];
            if (isMergeRuleAfter(rule) && rule.after === itemA.name) {
                merged.push(itemB.name);
                processedB.add(itemB.name);
            }
        }
    }

    // Add remaining B items that have no rules
    for (const itemB of flatB) {
        if (!processedB.has(itemB.name)) {
            merged.push(itemB.name);
            processedB.add(itemB.name);
        }
    }

    const result: SystemOrder = [];
    let currentGroup: (string | number | symbol)[] | null = null;

    for (const name of merged) {
        const isAsyncA = isAsync(name.toString());
        const isAsyncB = isAsync(name.toString());
        const shouldBeInGroup = isAsyncA || isAsyncB;

        if (shouldBeInGroup) {
            if (currentGroup === null) {
                currentGroup = [name];
                result.push(currentGroup);
            } else {
                currentGroup.push(name);
            }
        } else {
            currentGroup = null;
            result.push(name);
        }
    }

    return result;
}

type GenericSystemForStage<S extends SystemStage> = System<S> | AsyncSystem<S>;

export function getSortedSystemsByStage<Systems extends Record<string, System | AsyncSystem>>(
    graph: SystemGraph<
        Systems,
        {
            [S in SystemStage]: (keyof Systems | (keyof Systems)[])[];
        }
    >,
): {
    systemsByStage: { [S in SystemStage]: (GenericSystemForStage<S> | GenericSystemForStage<S>[])[] };
    nameToStageAndIndex: Record<string, { stage: SystemStage; index: [number] | [number, number] }>;
} {
    const nameToStageAndIndex: Record<string, { stage: SystemStage; index: [number] | [number, number] }> = {};

    function map<SS extends SystemStage>(
        systemName: (string | number | symbol) | (string | number | symbol)[],
        idx: number,
    ): (GenericSystemForStage<SS> | GenericSystemForStage<SS>[])[] {
        if (Array.isArray(systemName))
            return systemName.map((n, idx2) => {
                const system = graph.systems[n.toString()];
                nameToStageAndIndex[n.toString()] = { stage: system.stage, index: [idx, idx2] };
                return system;
            }) as never;

        const system = graph.systems[systemName.toString()];
        nameToStageAndIndex[systemName.toString()] = { stage: system.stage, index: [idx] };
        return system as never;
    }

    const systemsByStage = {
        startup: graph.orderByStage.startup.map(map),
        update: graph.orderByStage.update.map(map),
        render: graph.orderByStage.render.map(map),
        cleanup: graph.orderByStage.cleanup.map(map),
    } as never;

    return {
        systemsByStage,
        nameToStageAndIndex,
    };
}
